### PR TITLE
add ptr-poker benchmarks

### PR DESCRIPTION
**Pull request by raehik**
Without changing anything else, on GHC 9.4, it looks like fumieval's mason wins most of these. ptr-poker has some poor scaling and rarely wins.

### CODE REVIEW

**Comment by raehik** [comment]
The results on the readme should be updated too, I hadn't realized mason had been added (and was beating the competition).

**Comment by raehik** [comment]
I have a feeling mason wins out due to its intricate unboxing ([Mason.Builder.Internal](https://github.com/fumieval/mason/blob/3b11fe0d94da35950294aced25bb3fcbed34b0ff/src/Mason/Builder/Internal.hs)):

```haskell

-- | The Builder type. Requires RankNTypes extension
type Builder = forall s. Buildable s => BuilderFor s

-- | Builder specialised for a backend
newtype BuilderFor s = RawBuilder { unRawBuilder :: s -> BState -> BState }

unBuilder :: BuilderFor s -> s -> Buffer -> IO Buffer
unBuilder (RawBuilder f) = \env (Buffer (Ptr ptr) (Ptr end)) -> IO (\s -> case f env (# ptr, end, s #) of
   (# ptr', end', s' #) -> (# s', Buffer (Ptr ptr') (Ptr end') #))
{-# INLINE unBuilder #-}

pattern Builder :: (s -> Buffer -> IO Buffer) -> BuilderFor s
pattern Builder f <- (unBuilder -> f) where
  Builder f = RawBuilder $ \env (# ptr, end, s #) -> case unIO (f env (Buffer (Ptr ptr) (Ptr end))) s of
    (# s', Buffer (Ptr ptr') (Ptr end') #) -> (# ptr', end', s' #)

{-# COMPLETE Builder #-}

type BState = (#Addr#, Addr#, State# RealWorld #)
```

It would be nice to have a restricted serializer using ptr-poker/store's design that performs better in certain scenarios.

**Comment by raehik** [comment]
I have a WIP design that mostly works like ptr-poker with "manual" IO like mason does. It wins all the `averagedAppends` benchmarks, and has similarly poor performance (to ptr-poker) on large sizes of `regularConcat`. Perhaps that sort of operation does poorly with unbuffered serialization.

**Comment by nikita-volkov** [comment]
Thanks! Could you also include an update to the results in README?

**Comment by nikita-volkov** [comment]
Regarding unboxing. Yep it might help.

Also do take into account that the benchmarks are pretty synthetic. So PRs extending the suite to include more representative benchmarks are very much welcome.

**Comment by raehik** [comment]
I've cleaned up this PR. ptr-poker benchmarks are added, and the readme results are regenerated. (I added Nix building largely for my own convenience, I would gladly remove.) I'll work on my own unboxed serializer elsewhere.

**Pull request merged**
